### PR TITLE
added social links

### LINKED ISSUE #61: Adding Social links
Social links will help connect with the community so they are a must

would like to add it in footer under hactoberfest

### PR DESCRIPTION
**Pull request by Bhavishya2601**
Fixes #61

### CODE REVIEW

**Comment by aialok** [comment]
@Bhavishya2601  where is hyperlink?

please update with hacktoberfest social link : )

**Comment by Bhavishya2601** [comment]
@aialok  i have added the anchor tags in all the icons
i don't have your social media links, either you can merge it and then add the links or you can provide me with all the links of the social media, I'll add it

**Comment by aialok** [comment]
> @aialok  i have added the anchor tags in all the icons
> i don't have your social media links, either you can merge it and then add the links or you can provide me with all the links of the social media, I'll add it

Go to hacktoberfest website and add those link.

**Comment by Bhavishya2601** [comment]
@aialok done

**Review by aialok — APPROVED** [review]

**Pull request merged**
